Batter.create!(
   [
      {
         name: '森 友哉(西)',
         picture_id: '0',
         league: 'true',
         game: '135',
         pa: '573',
         ab: '492',
         hit: '162',
         hit_2b: '34',
         hit_3b: '2',
         hr: '23',
         tb: '269',
         rbi: '105',
         run: '96',
         so: '89',
         bb: '72',
         ibb: '3',
         hbp: '2',
         sh: '1',
         sf: '6',
         sb: '3',
         cs: '2',
         gdp: '9'
      },
      {
         name: '吉田 正尚（オ）',
         picture_id: '2',
         league: 'true',
         game: '143',
         pa: '610',
         ab: '521',
         hit: '168',
         hit_2b: '24',
         hit_3b: '2',
         hr: '29',
         tb: '283',
         rbi: '85',
         run: '92',
         so: '64',
         bb: '79',
         ibb: '12',
         hbp: '5',
         sh: '0',
         sf: '5',
         sb: '5',
         cs: '1',
         gdp: '12'
      },
      {
         name: '荻野 貴司（ロ）',
         picture_id: '3',
         league: 'true',
         game: '125',
         pa: '569',
         ab: '508',
         hit: '160',
         hit_2b: '35',
         hit_3b: '7',
         hr: '10',
         tb: '239',
         rbi: '46',
         run: '76',
         so: '56',
         bb: '40',
         ibb: '1',
         hbp: '8',
         sh: '9',
         sf: '4',
         sb: '28',
         cs: '10',
         gdp: '4'
      },
      {
         name: '鈴木 誠也（広）',
         picture_id: '5',
         league: 'false',
         game: '140',
         pa: '612',
         ab: '499',
         hit: '167',
         hit_2b: '31',
         hit_3b: '0',
         hr: '28',
         tb: '282',
         rbi: '87',
         run: '112',
         so: '81',
         bb: '103',
         ibb: '12',
         hbp: '7',
         sh: '0',
         sf: '3',
         sb: '25',
         cs: '16',
         gdp: '3'
      }, 
      {
         name: 'ビシエド（中）',
         picture_id: '1',
         league: 'false',
         game: '143',
         pa: '594',
         ab: '534',
         hit: '168',
         hit_2b: '43',
         hit_3b: '0',
         hr: '18',
         tb: '265',
         rbi: '93',
         run: '56',
         so: '88',
         bb: '41',
         ibb: '9',
         hbp: '13',
         sh: '0',
         sf: '6',
         sb: '2',
         cs: '1',
         gdp: '2'
      },
      {
         name: '糸井 嘉男（神）',
         picture_id: '1',
         league: 'false',
         game: '103',
         pa: '444',
         ab: '382',
         hit: '120',
         hit_2b: '22',
         hit_3b: '1',
         hr: '5',
         tb: '159',
         rbi: '42',
         run: '45',
         so: '63',
         bb: '52',
         ibb: '7',
         hbp: '7',
         sh: '0',
         sf: '3',
         sb: '9',
         cs: '5',
         gdp: '1'
      }
   ]
)

Pitcher.create!(
   [
      {
         name: '大野 雄大(中)',
         picture_id: '1',
         league: 'false',
         win: '9',
         lose: '8',
         game: '25',
         cg: '2',
         sho: '2',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '533',
         tbf: '696',
         hit: '132',
         hr: '18',
         so: '156',
         bb: '43',
         hbp: '2',
         wp: '2',
         bk: '0',
         r: '52',
         er: '51',
         fip: '3.70'
      },
      {
         name: 'ジョンソン（広）',
         picture_id: '5',
         league: 'false',
         win: '11',
         lose: '8',
         game: '27',
         cg: '1',
         sho: '1',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '470',
         tbf: '-',
         hit: '132',
         hr: '12',
         so: '132',
         bb: '58',
         hbp: '4',
         wp: '3',
         bk: '0',
         r: '50',
         er: '45',
         fip: '3.87'
      },
      {
         name: '山口 俊 （巨）',
         picture_id: '6',
         league: 'false',
         win: '15',
         lose: '4',
         game: '26',
         cg: '0',
         sho: '0',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '510',
         tbf: '-',
         hit: '137',
         hr: '8',
         so: '188',
         bb: '60',
         hbp: '13',
         wp: '4',
         bk: '0',
         r: '60',
         er: '55',
         fip: '3.08'
      },
      {
         name: '山本 由伸（オ）',
         picture_id: '7',
         league: 'true',
         win: '8',
         lose: '6',
         game: '20',
         cg: '1',
         sho: '1',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '429',
         tbf: '-',
         hit: '101',
         hr: '8',
         so: '127',
         bb: '36',
         hbp: '3',
         wp: '3',
         bk: '1',
         r: '37',
         er: '31',
         fip: '3.09'
      },
      {
         name: '有原 航平（日）',
         picture_id: '8',
         league: 'true',
         win: '15',
         lose: '8',
         game: '24',
         cg: '1',
         sho: '1',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '493',
         tbf: '-',
         hit: '111',
         hr: '14',
         so: '161',
         bb: '40',
         hbp: '9',
         wp: '9',
         bk: '0',
         r: '49',
         er: '45',
         fip: '3.36'
      },
      {
         name: '千賀 滉大（ソ）',
         picture_id: '9',
         league: 'true',
         win: '13',
         lose: '8',
         game: '26',
         cg: '2',
         sho: '2',
         qs: '20',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '541',
         tbf: '-',
         hit: '134',
         hr: '19',
         so: '227',
         bb: '75',
         hbp: '8',
         wp: '4',
         bk: '1',
         r: '60',
         er: '56',
         fip: '3.36'
      }
   ]
)