Batter.create!(
   [
      {
         name: '森 友哉(西)',
         picture_id: '0',
         league: 'true',
         game: '135',
         pa: '573',
         ab: '492',
         hit: '162',
         hit_2b: '34',
         hit_3b: '2',
         hr: '23',
         tb: '269',
         rbi: '105',
         run: '96',
         so: '89',
         bb: '72',
         ibb: '3',
         hbp: '2',
         sh: '1',
         sf: '6',
         sb: '3',
         cs: '2',
         gdp: '9'
      },
      {
         name: '吉田 正尚（オ）',
         picture_id: '2',
         league: 'true',
         game: '143',
         pa: '610',
         ab: '521',
         hit: '168',
         hit_2b: '24',
         hit_3b: '2',
         hr: '29',
         tb: '283',
         rbi: '85',
         run: '92',
         so: '64',
         bb: '79',
         ibb: '12',
         hbp: '5',
         sh: '0',
         sf: '5',
         sb: '5',
         cs: '1',
         gdp: '12'
      },
      {
         name: '荻野 貴司（ロ）',
         picture_id: '3',
         league: 'true',
         game: '125',
         pa: '569',
         ab: '508',
         hit: '160',
         hit_2b: '35',
         hit_3b: '7',
         hr: '10',
         tb: '239',
         rbi: '46',
         run: '76',
         so: '56',
         bb: '40',
         ibb: '1',
         hbp: '8',
         sh: '9',
         sf: '4',
         sb: '28',
         cs: '10',
         gdp: '4'
      }
   ]
)

Pitcher.create!(
   [
      {
         name: '大野 雄大(中)',
         picture_id: '1',
         league: 'false',
         win: '9',
         lose: '8',
         game: '25',
         cg: '2',
         sho: '2',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '533',
         tbf: '696',
         hit: '132',
         hr: '18',
         so: '156',
         bb: '43',
         hbp: '2',
         wp: '2',
         bk: '0',
         r: '52',
         er: '51',
         fip: '3.70'
      },
      {
         name: 'ジョンソン（広）',
         picture_id: '5',
         league: 'false',
         win: '11',
         lose: '8',
         game: '27',
         cg: '1',
         sho: '1',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '470',
         tbf: '-',
         hit: '132',
         hr: '12',
         so: '132',
         bb: '58',
         hbp: '4',
         wp: '3',
         bk: '0',
         r: '50',
         er: '45',
         fip: '3.87'
      },
      {
         name: '山口 俊 （巨）',
         picture_id: '6',
         league: 'false',
         win: '15',
         lose: '4',
         game: '26',
         cg: '0',
         sho: '0',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '510',
         tbf: '-',
         hit: '137',
         hr: '8',
         so: '188',
         bb: '60',
         hbp: '13',
         wp: '4',
         bk: '0',
         r: '60',
         er: '55',
         fip: '3.08'
      }
   ]
)