User.create!(
   email: 'abc@abc',
   password: 'foobar'
   )
Batter.create!(
   [
      {
         name: '森 友哉（西）',
         picture: open("#{Rails.root}/db/fixtures/batter_1.jpg"),
         league: 'true',
         game: '135',
         pa: '573',
         ab: '492',
         hit: '162',
         hit_2b: '34',
         hit_3b: '2',
         hr: '23',
         tb: '269',
         rbi: '105',
         run: '96',
         so: '89',
         bb: '72',
         ibb: '3',
         hbp: '2',
         sh: '1',
         sf: '6',
         sb: '3',
         cs: '2',
         gdp: '9'
      },
      {
         name: '吉田 正尚（オ）',
         picture: open("#{Rails.root}/db/fixtures/batter_2.jpg"),
         league: 'true',
         game: '143',
         pa: '610',
         ab: '521',
         hit: '168',
         hit_2b: '24',
         hit_3b: '2',
         hr: '29',
         tb: '283',
         rbi: '85',
         run: '92',
         so: '64',
         bb: '79',
         ibb: '12',
         hbp: '5',
         sh: '0',
         sf: '5',
         sb: '5',
         cs: '1',
         gdp: '12'
      },
      {
         name: '荻野 貴司（ロ）',
         picture: open("#{Rails.root}/db/fixtures/1000014_s.jpg"),
         league: 'true',
         game: '125',
         pa: '569',
         ab: '508',
         hit: '160',
         hit_2b: '35',
         hit_3b: '7',
         hr: '10',
         tb: '239',
         rbi: '46',
         run: '76',
         so: '56',
         bb: '40',
         ibb: '1',
         hbp: '8',
         sh: '9',
         sf: '4',
         sb: '28',
         cs: '10',
         gdp: '4'
      },
      {
         name: '銀次（楽）',
         picture: open("#{Rails.root}/db/fixtures/600020_s.jpg"),
         league: 'true',
         game: '141',
         pa: '590',
         ab: '529',
         hit: '161',
         hit_2b: '24',
         hit_3b: '1',
         hr: '5',
         tb: '202',
         rbi: '56',
         run: '56',
         so: '58',
         bb: '52',
         ibb: '2',
         hbp: '4',
         sh: '4',
         sf: '1',
         sb: '2',
         cs: '5',
         gdp: '1'
      },
      {
         name: '秋山 翔吾（西)',
         picture: open("#{Rails.root}/db/fixtures/1000150_s.jpg"),
         league: 'true',
         game: '143',
         pa: '678',
         ab: '590',
         hit: '179',
         hit_2b: '31',
         hit_3b: '4',
         hr: '20',
         tb: '278',
         rbi: '62',
         run: '112',
         so: '108',
         bb: '78',
         ibb: '2',
         hbp: '9',
         sh: '0',
         sf: '1',
         sb: '12',
         cs: '8',
         gdp: '8'
      },
      {
         name: '近藤 健介（日）',
         picture: open("#{Rails.root}/db/fixtures/1100097_s.jpg"),
         league: 'true',
         game: '138',
         pa: '600',
         ab: '490',
         hit: '148',
         hit_2b: '32',
         hit_3b: '5',
         hr: '2',
         tb: '196',
         rbi: '59',
         run: '74',
         so: '81',
         bb: '103',
         ibb: '3',
         hbp: '2',
         sh: '0',
         sf: '5',
         sb: '1',
         cs: '4',
         gdp: '1'
      },
      {
         name: '大田 泰示（日）',
         picture: open("#{Rails.root}/db/fixtures/900011_s.jpg"),
         league: 'true',
         game: '132',
         pa: '594',
         ab: '557',
         hit: '161',
         hit_2b: '28',
         hit_3b: '1',
         hr: '20',
         tb: '251',
         rbi: '77',
         run: '79',
         so: '111',
         bb: '27',
         ibb: '4',
         hbp: '5',
         sh: '0',
         sf: '5',
         sb: '6',
         cs: '2',
         gdp: '2'
      },
      {
         name: '鈴木 大地（ロ）',
         picture: open("#{Rails.root}/db/fixtures/1100103_s.jpg"),
         league: 'true',
         game: '140',
         pa: '614',
         ab: '527',
         hit: '152',
         hit_2b: '34',
         hit_3b: '4',
         hr: '15',
         tb: '239',
         rbi: '68',
         run: '76',
         so: '75',
         bb: '56',
         ibb: '0',
         hbp: '16',
         sh: '13',
         sf: '2',
         sb: '3',
         cs: '1',
         gdp: '1'
      },
      {
         name: '西川 遥輝（日）',
         picture: open("#{Rails.root}/db/fixtures/1000100_s.jpg"),
         league: 'true',
         game: '142',
         pa: '651',
         ab: '548',
         hit: '158',
         hit_2b: '26',
         hit_3b: '6',
         hr: '5',
         tb: '211',
         rbi: '41',
         run: '88',
         so: '111',
         bb: '93',
         ibb: '2',
         hbp: '2',
         sh: '8',
         sf: '0',
         sb: '19',
         cs: '5',
         gdp: '5'
      },
      {
         name: '島内 宏明（楽）',
         picture: open("#{Rails.root}/db/fixtures/1100132_s.jpg"),
         league: 'true',
         game: '133',
         pa: '585',
         ab: '506',
         hit: '145',
         hit_2b: '21',
         hit_3b: '5',
         hr: '10',
         tb: '206',
         rbi: '57',
         run: '68',
         so: '65',
         bb: '58',
         ibb: '0',
         hbp: '11',
         sh: '9',
         sf: '1',
         sb: '3',
         cs: '4',
         gdp: '11'
      },
      {
         name: '中村 剛也（西）',
         picture: open("#{Rails.root}/db/fixtures/12101_s.jpg"),
         league: 'true',
         game: '135',
         pa: '557',
         ab: '496',
         hit: '142',
         hit_2b: '30',
         hit_3b: '0',
         hr: '30',
         tb: '262',
         rbi: '123',
         run: '69',
         so: '123',
         bb: '54',
         ibb: '5',
         hbp: '4',
         sh: '0',
         sf: '3',
         sb: '2',
         cs: '1',
         gdp: '12'
      },
      {
         name: '茂木 栄五郎（楽）',
         picture: open("#{Rails.root}/db/fixtures/1600003_s.jpg"),
         league: 'true',
         game: '141',
         pa: '648',
         ab: '568',
         hit: '160',
         hit_2b: '28',
         hit_3b: '6',
         hr: '13',
         tb: '239',
         rbi: '55',
         run: '86',
         so: '121',
         bb: '66',
         ibb: '1',
         hbp: '3',
         sh: '9',
         sf: '2',
         sb: '7',
         cs: '5',
         gdp: '7'
      },
      {
         name: '源田 壮亮（西）',
         picture: open("#{Rails.root}/db/fixtures/1600129_s.jpg"),
         league: 'true',
         game: '135',
         pa: '609',
         ab: '540',
         hit: '148',
         hit_2b: '23',
         hit_3b: '6',
         hr: '2',
         tb: '189',
         rbi: '41',
         run: '90',
         so: '67',
         bb: '40',
         ibb: '0',
         hbp: '1',
         sh: '25',
         sf: '3',
         sb: '30',
         cs: '9',
         gdp: '9'
      },
      {
         name: '外崎 修汰（西）',
         picture: open("#{Rails.root}/db/fixtures/1400184_s.jpg"),
         league: 'true',
         game: '143',
         pa: '621',
         ab: '533',
         hit: '146',
         hit_2b: '27',
         hit_3b: '6',
         hr: '26',
         tb: '263',
         rbi: '90',
         run: '96',
         so: '132',
         bb: '63',
         ibb: '0',
         hbp: '5',
         sh: '14',
         sf: '6',
         sb: '22',
         cs: '6',
         gdp: '9'
      },
      {
         name: '浅村 栄斗（楽）',
         picture: open("#{Rails.root}/db/fixtures/900056_s.jpg"),
         league: 'true',
         game: '143',
         pa: '635',
         ab: '529',
         hit: '139',
         hit_2b: '26',
         hit_3b: '2',
         hr: '33',
         tb: '268',
         rbi: '92',
         run: '93',
         so: '162',
         bb: '93',
         ibb: '9',
         hbp: '4',
         sh: '0',
         sf: '9',
         sb: '1',
         cs: '1',
         gdp: '12'
      },
      {
         name: '渡邉 諒（日)',
         picture: open("#{Rails.root}/db/fixtures/1300042_s.jpg"),
         league: 'true',
         game: '132',
         pa: '543',
         ab: '481',
         hit: '126',
         hit_2b: '16',
         hit_3b: '5',
         hr: '11',
         tb: '185',
         rbi: '58',
         run: '60',
         so: '120',
         bb: '48',
         ibb: '0',
         hbp: '6',
         sh: '3',
         sf: '5',
         sb: '0',
         cs: '2',
         gdp: '8'
      },
      {
         name: 'ブラッシュ（楽）',
         picture: open("#{Rails.root}/db/fixtures/1800132_s.jpg"),
         league: 'true',
         game: '128',
         pa: '527',
         ab: '426',
         hit: '111',
         hit_2b: '20',
         hit_3b: '0',
         hr: '33',
         tb: '230',
         rbi: '95',
         run: '66',
         so: '157',
         bb: '81',
         ibb: '2',
         hbp: '17',
         sh: '0',
         sf: '3',
         sb: '2',
         cs: '3',
         gdp: '7'
      },
      {
         name: '松田 宣浩（ソ）',
         picture: open("#{Rails.root}/db/fixtures/600084_s.jpg"),
         league: 'true',
         game: '143',
         pa: '576',
         ab: '534',
         hit: '139',
         hit_2b: '25',
         hit_3b: '2',
         hr: '30',
         tb: '258',
         rbi: '76',
         run: '64',
         so: '115',
         bb: '33',
         ibb: '4',
         hbp: '3',
         sh: '2',
         sf: '4',
         sb: '5',
         cs: '3',
         gdp: '14'
      },
      {
         name: '甲斐 拓也（ソ）',
         picture: open("#{Rails.root}/db/fixtures/1000176_s.jpg"),
         league: 'true',
         game: '137',
         pa: '454',
         ab: '377',
         hit: '98',
         hit_2b: '15',
         hit_3b: '0',
         hr: '11',
         tb: '146',
         rbi: '43',
         run: '42',
         so: '114',
         bb: '50',
         ibb: '0',
         hbp: '1',
         sh: '23',
         sf: '3',
         sb: '9',
         cs: '4',
         gdp: '9'
      },
      {
         name: 'デスパイネ（ソ）',
         picture: open("#{Rails.root}/db/fixtures/1400016_s.jpg"),
         league: 'true',
         game: '130',
         pa: '519',
         ab: '448',
         hit: '116',
         hit_2b: '9',
         hit_3b: '0',
         hr: '36',
         tb: '233',
         rbi: '88',
         run: '61',
         so: '119',
         bb: '63',
         ibb: '1',
         hbp: '5',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '1',
         gdp: '6'
      },
      {
         name: '内川 聖一（ソ）',
         picture: open("#{Rails.root}/db/fixtures/11983_s.jpg"),
         league: 'true',
         game: '137',
         pa: '535',
         ab: '500',
         hit: '128',
         hit_2b: '21',
         hit_3b: '0',
         hr: '12',
         tb: '185',
         rbi: '41',
         run: '49',
         so: '49',
         bb: '28',
         ibb: '1',
         hbp: '2',
         sh: '1',
         sf: '4',
         sb: '3',
         cs: '0',
         gdp: '16'
      },
      {
         name: '山川 穂高（西）',
         picture: open("#{Rails.root}/db/fixtures/1300101_s.jpg"),
         league: 'true',
         game: '143',
         pa: '626',
         ab: '524',
         hit: '134',
         hit_2b: '20',
         hit_3b: '0',
         hr: '43',
         tb: '283',
         rbi: '120',
         run: '93',
         so: '142',
         bb: '86',
         ibb: '8',
         hbp: '13',
         sh: '0',
         sf: '3',
         sb: '1',
         cs: '0',
         gdp: '13'
      },
      {
         name: '栗山 巧（西）',
         picture: open("#{Rails.root}/db/fixtures/12102_s.jpg"),
         league: 'true',
         game: '123',
         pa: '466',
         ab: '409',
         hit: '103',
         hit_2b: '21',
         hit_3b: '0',
         hr: '7',
         tb: '145',
         rbi: '54',
         run: '35',
         so: '100',
         bb: '48',
         ibb: '2',
         hbp: '3',
         sh: '3',
         sf: '3',
         sb: '0',
         cs: '0',
         gdp: '13'
      },
      {
         name: '井上 晴哉（ロ）',
         picture: open("#{Rails.root}/db/fixtures/1300054_s.jpg"),
         league: 'true',
         game: '129',
         pa: '509',
         ab: '429',
         hit: '108',
         hit_2b: '16',
         hit_3b: '1',
         hr: '24',
         tb: '198',
         rbi: '65',
         run: '60',
         so: '98',
         bb: '67',
         ibb: '1',
         hbp: '9',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '0',
         gdp: '10'
      },
      {
         name: '金子 侑司（西）',
         picture: open("#{Rails.root}/db/fixtures/1200083_s.jpg"),
         league: 'true',
         game: '133',
         pa: '524',
         ab: '463',
         hit: '116',
         hit_2b: '8',
         hit_3b: '1',
         hr: '3',
         tb: '135',
         rbi: '33',
         run: '60',
         so: '81',
         bb: '49',
         ibb: '1',
         hbp: '3',
         sh: '6',
         sf: '3',
         sb: '41',
         cs: '10',
         gdp: '3'
      },
      {
         name: '福田 周平（オ）',
         picture: open("#{Rails.root}/db/fixtures/1700111_s.jpg"),
         league: 'true',
         game: '135',
         pa: '583',
         ab: '492',
         hit: '123',
         hit_2b: '13',
         hit_3b: '5',
         hr: '2',
         tb: '152',
         rbi: '38',
         run: '68',
         so: '57',
         bb: '62',
         ibb: '0',
         hbp: '8',
         sh: '19',
         sf: '2',
         sb: '30',
         cs: '14',
         gdp: '7'
      },
      {
         name: 'レアード（ロ）',
         picture: open("#{Rails.root}/db/fixtures/1500012_s.jpg"),
         league: 'true',
         game: '139',
         pa: '553',
         ab: '487',
         hit: '121',
         hit_2b: '18',
         hit_3b: '0',
         hr: '32',
         tb: '235',
         rbi: '89',
         run: '59',
         so: '128',
         bb: '55',
         ibb: '2',
         hbp: '8',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '0',
         gdp: '18'
      },
      {
         name: 'ウィーラー（楽）',
         picture: open("#{Rails.root}/db/fixtures/1500015_s.jpg"),
         league: 'true',
         game: '117',
         pa: '472',
         ab: '411',
         hit: '100',
         hit_2b: '15',
         hit_3b: '0',
         hr: '19',
         tb: '172',
         rbi: '67',
         run: '53',
         so: '96',
         bb: '43',
         ibb: '0',
         hbp: '8',
         sh: '0',
         sf: '10',
         sb: '3',
         cs: '5',
         gdp: '22'
      },
      {
         name: '中田 翔（日）',
         picture: open("#{Rails.root}/db/fixtures/800054_s.jpg"),
         league: 'true',
         game: '124',
         pa: '514',
         ab: '450',
         hit: '109',
         hit_2b: '21',
         hit_3b: '0',
         hr: '24',
         tb: '202',
         rbi: '80',
         run: '55',
         so: '83',
         bb: '55',
         ibb: '4',
         hbp: '5',
         sh: '0',
         sf: '4',
         sb: '0',
         cs: '0',
         gdp: '16'
      },
      {
         name: '中村 奨吾（ロ）',
         picture: open("#{Rails.root}/db/fixtures/1400188_s.jpg"),
         league: 'true',
         game: '143',
         pa: '586',
         ab: '512',
         hit: '119',
         hit_2b: '22',
         hit_3b: '0',
         hr: '17',
         tb: '192',
         rbi: '59',
         run: '68',
         so: '96',
         bb: '53',
         ibb: '2',
         hbp: '12',
         sh: '6',
         sf: '3',
         sb: '12',
         cs: '6',
         gdp: '10'
      },
      {
         name: '鈴木 誠也（広）',
         picture: open("#{Rails.root}/db/fixtures/1200069_s.jpg"),
         league: 'false',
         game: '140',
         pa: '612',
         ab: '499',
         hit: '167',
         hit_2b: '31',
         hit_3b: '0',
         hr: '28',
         tb: '282',
         rbi: '87',
         run: '112',
         so: '81',
         bb: '103',
         ibb: '12',
         hbp: '7',
         sh: '0',
         sf: '3',
         sb: '25',
         cs: '16',
         gdp: '3'
      }, 
      {
         name: 'ビシエド（中）',
         picture: open("#{Rails.root}/db/fixtures/1600021_s.jpg"),
         league: 'false',
         game: '143',
         pa: '594',
         ab: '534',
         hit: '168',
         hit_2b: '43',
         hit_3b: '0',
         hr: '18',
         tb: '265',
         rbi: '93',
         run: '56',
         so: '88',
         bb: '41',
         ibb: '9',
         hbp: '13',
         sh: '0',
         sf: '6',
         sb: '2',
         cs: '1',
         gdp: '2'
      },
      {
         name: '糸井 嘉男（神）',
         picture: open("#{Rails.root}/db/fixtures/400057_s.jpg"),
         league: 'false',
         game: '103',
         pa: '444',
         ab: '382',
         hit: '120',
         hit_2b: '22',
         hit_3b: '1',
         hr: '5',
         tb: '159',
         rbi: '42',
         run: '45',
         so: '63',
         bb: '52',
         ibb: '7',
         hbp: '7',
         sh: '0',
         sf: '3',
         sb: '9',
         cs: '5',
         gdp: '1'
      },
      {
         name: '大島 洋平（中）',
         picture: open("#{Rails.root}/db/fixtures/900410_s.jpg"),
         league: 'false',
         game: '143',
         pa: '623',
         ab: '558',
         hit: '174',
         hit_2b: '23',
         hit_3b: '3',
         hr: '3',
         tb: '212',
         rbi: '45',
         run: '89',
         so: '78',
         bb: '50',
         ibb: '3',
         hbp: '9',
         sh: '3',
         sf: '3',
         sb: '30',
         cs: '7',
         gdp: '5'
      },
      {
         name: '坂本 勇人（巨）',
         picture: open("#{Rails.root}/db/fixtures/700003_s.jpg"),
         league: 'false',
         game: '143',
         pa: '639',
         ab: '555',
         hit: '173',
         hit_2b: '26',
         hit_3b: '0',
         hr: '40',
         tb: '319',
         rbi: '94',
         run: '103',
         so: '123',
         bb: '77',
         ibb: '6',
         hbp: '2',
         sh: '3',
         sf: '2',
         sb: '5',
         cs: '3',
         gdp: '9'
      },
      {
         name: '西川 龍馬（広）',
         picture: open("#{Rails.root}/db/fixtures/1500096_s.jpg"),
         league: 'false',
         game: '138',
         pa: '585',
         ab: '535',
         hit: '159',
         hit_2b: '23',
         hit_3b: '3',
         hr: '16',
         tb: '236',
         rbi: '64',
         run: '70',
         so: '81',
         bb: '32',
         ibb: '4',
         hbp: '2',
         sh: '11',
         sf: '5',
         sb: '6',
         cs: '7',
         gdp: '9'
      },
      {
         name: '青木 宣親（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/400021_s.jpg"),
         league: 'false',
         game: '134',
         pa: '565',
         ab: '489',
         hit: '145',
         hit_2b: '19',
         hit_3b: '2',
         hr: '16',
         tb: '216',
         rbi: '58',
         run: '84',
         so: '72',
         bb: '61',
         ibb: '2',
         hbp: '11',
         sh: '1',
         sf: '3',
         sb: '1',
         cs: '2',
         gdp: '13'
      },
      {
         name: '高橋 周平（中）',
         picture: open("#{Rails.root}/db/fixtures/1100069_s.jpg"),
         league: 'false',
         game: '117',
         pa: '471',
         ab: '430',
         hit: '126',
         hit_2b: '28',
         hit_3b: '5',
         hr: '7',
         tb: '185',
         rbi: '59',
         run: '50',
         so: '70',
         bb: '32',
         ibb: '7',
         hbp: '3',
         sh: '5',
         sf: '1',
         sb: '3',
         cs: '4',
         gdp: '10'
      },
      {
         name: '丸 佳浩（巨）',
         picture: open("#{Rails.root}/db/fixtures/800043_s.jpg"),
         league: 'false',
         game: '143',
         pa: '631',
         ab: '535',
         hit: '156',
         hit_2b: '26',
         hit_3b: '1',
         hr: '27',
         tb: '265',
         rbi: '89',
         run: '82',
         so: '125',
         bb: '86',
         ibb: '3',
         hbp: '3',
         sh: '0',
         sf: '7',
         sb: '12',
         cs: '5',
         gdp: '15'
      },
      {
         name: '阿部 寿樹（中）',
         picture: open("#{Rails.root}/db/fixtures/1500078_s.jpg"),
         league: 'false',
         game: '129',
         pa: '484',
         ab: '447',
         hit: '130',
         hit_2b: '24',
         hit_3b: '3',
         hr: '7',
         tb: '181',
         rbi: '59',
         run: '51',
         so: '82',
         bb: '31',
         ibb: '3',
         hbp: '1',
         sh: '3',
         sf: '2',
         sb: '1',
         cs: '0',
         gdp: '9'
      },
      {
         name: '亀井 善行（巨）',
         picture: open("#{Rails.root}/db/fixtures/500037_s.jpg"),
         league: 'false',
         game: '131',
         pa: '503',
         ab: '450',
         hit: '128',
         hit_2b: '27',
         hit_3b: '2',
         hr: '13',
         tb: '198',
         rbi: '55',
         run: '67',
         so: '91',
         bb: '45',
         ibb: '3',
         hbp: '0',
         sh: '3',
         sf: '5',
         sb: '9',
         cs: '1',
         gdp: '6'
      },
      {
         name: '宮﨑 敏郎（De）',
         picture: open("#{Rails.root}/db/fixtures/1200053_s.jpg"),
         league: 'false',
         game: '114',
         pa: '473',
         ab: '433',
         hit: '123',
         hit_2b: '22',
         hit_3b: '1',
         hr: '15',
         tb: '192',
         rbi: '49',
         run: '54',
         so: '35',
         bb: '32',
         ibb: '2',
         hbp: '3',
         sh: '0',
         sf: '5',
         sb: '0',
         cs: '0',
         gdp: '13'
      },
      {
         name: 'バレンティン（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/500480_s.jpg"),
         league: 'false',
         game: '120',
         pa: '468',
         ab: '410',
         hit: '115',
         hit_2b: '13',
         hit_3b: '0',
         hr: '33',
         tb: '227',
         rbi: '93',
         run: '65',
         so: '117',
         bb: '54',
         ibb: '3',
         hbp: '1',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '1',
         gdp: '11'
      },
      {
         name: '神里 和毅（De）',
         picture: open("#{Rails.root}/db/fixtures/1700059_s.jpg"),
         league: 'false',
         game: '123',
         pa: '458',
         ab: '427',
         hit: '119',
         hit_2b: '31',
         hit_3b: '3',
         hr: '6',
         tb: '174',
         rbi: '35',
         run: '62',
         so: '121',
         bb: '26',
         ibb: '2',
         hbp: '2',
         sh: '3',
         sf: '0',
         sb: '15',
         cs: '10',
         gdp: '7'
      },
      {
         name: '  會澤 翼（広）',
         picture: open("#{Rails.root}/db/fixtures/700050_s.jpg"),
         league: 'false',
         game: '126',
         pa: '447',
         ab: '376',
         hit: '104',
         hit_2b: '21',
         hit_3b: '2',
         hr: '12',
         tb: '165',
         rbi: '63',
         run: '38',
         so: '81',
         bb: '58',
         ibb: '5',
         hbp: '10',
         sh: '3',
         sf: '0',
         sb: '2',
         cs: '1',
         gdp: '6'
      },
      {
         name: '雄平（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/20127_s.jpg"),
         league: 'false',
         game: '131',
         pa: '493',
         ab: '447',
         hit: '122',
         hit_2b: '19',
         hit_3b: '0',
         hr: '12',
         tb: '177',
         rbi: '56',
         run: '55',
         so: '71',
         bb: '37',
         ibb: '4',
         hbp: '2',
         sh: '1',
         sf: '6',
         sb: '4',
         cs: '3',
         gdp: '4'
      },
      {
         name: '筒香 嘉智（De）',
         picture: open("#{Rails.root}/db/fixtures/1000002_s.jpg"),
         league: 'false',
         game: '131',
         pa: '557',
         ab: '464',
         hit: '126',
         hit_2b: '24',
         hit_3b: '0',
         hr: '29',
         tb: '237',
         rbi: '79',
         run: '74',
         so: '141',
         bb: '88',
         ibb: '5',
         hbp: '2',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '0',
         gdp: '5'
      },
      {
         name: '近本 光司（神）',
         picture: open("#{Rails.root}/db/fixtures/1800065_s.jpg"),
         league: 'false',
         game: '142',
         pa: '640',
         ab: '586',
         hit: '159',
         hit_2b: '20',
         hit_3b: '7',
         hr: '9',
         tb: '220',
         rbi: '42',
         run: '81',
         so: '110',
         bb: '31',
         ibb: '2',
         hbp: '6',
         sh: '14',
         sf: '3',
         sb: '36',
         cs: '15',
         gdp: '2'
      },
      {
         name: '山田 哲人（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/1000132_s.jpg"),
         league: 'false',
         game: '142',
         pa: '641',
         ab: '520',
         hit: '141',
         hit_2b: '35',
         hit_3b: '5',
         hr: '35',
         tb: '291',
         rbi: '98',
         run: '102',
         so: '121',
         bb: '110',
         ibb: '7',
         hbp: '6',
         sh: '0',
         sf: '5',
         sb: '33',
         cs: '3',
         gdp: '14'
      },
      {
         name: 'ソト（De）',
         picture: open("#{Rails.root}/db/fixtures/1700020_s.jpg"),
         league: 'false',
         game: '141',
         pa: '584',
         ab: '516',
         hit: '139',
         hit_2b: '18',
         hit_3b: '0',
         hr: '43',
         tb: '286',
         rbi: '108',
         run: '82',
         so: '98',
         bb: '59',
         ibb: '4',
         hbp: '5',
         sh: '0',
         sf: '4',
         sb: '0',
         cs: '0',
         gdp: '14'
      },
      {
         name: '中村 悠平（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/900044_s.jpg"),
         league: 'false',
         game: '126',
         pa: '450',
         ab: '372',
         hit: '100',
         hit_2b: '24',
         hit_3b: '2',
         hr: '5',
         tb: '143',
         rbi: '36',
         run: '42',
         so: '64',
         bb: '53',
         ibb: '3',
         hbp: '10',
         sh: '13',
         sf: '2',
         sb: '1',
         cs: '4',
         gdp: '11'
      },
      {
         name: '糸原 健斗（神）',
         picture: open("#{Rails.root}/db/fixtures/1600117_s.jpg"),
         league: 'false',
         game: '143',
         pa: '572',
         ab: '491',
         hit: '131',
         hit_2b: '20',
         hit_3b: '4',
         hr: '2',
         tb: '165',
         rbi: '45',
         run: '66',
         so: '70',
         bb: '60',
         ibb: '2',
         hbp: '7',
         sh: '11',
         sf: '3',
         sb: '6',
         cs: '5',
         gdp: '7'
      },
      {
         name: '梅野 隆太郎（神）',
         picture: open("#{Rails.root}/db/fixtures/1300073_s.jpg"),
         league: 'false',
         game: '129',
         pa: '492',
         ab: '433',
         hit: '115',
         hit_2b: '22',
         hit_3b: '3',
         hr: '9',
         tb: '170',
         rbi: '59',
         run: '49',
         so: '83',
         bb: '34',
         ibb: '4',
         hbp: '6',
         sh: '16',
         sf: '3',
         sb: '14',
         cs: '3',
         gdp: '16'
      },
      {
         name: '岡本 和真（巨）',
         picture: open("#{Rails.root}/db/fixtures/1400101_s.jpg"),
         league: 'false',
         game: '143',
         pa: '628',
         ab: '555',
         hit: '147',
         hit_2b: '29',
         hit_3b: '0',
         hr: '31',
         tb: '269',
         rbi: '94',
         run: '84',
         so: '132',
         bb: '62',
         ibb: '3',
         hbp: '6',
         sh: '2',
         sf: '3',
         sb: '3',
         cs: '0',
         gdp: '15'
      },
      {
         name: '菊池 涼介（広）',
         picture: open("#{Rails.root}/db/fixtures/1100082_s.jpg"),
         league: 'false',
         game: '138',
         pa: '619',
         ab: '547',
         hit: '143',
         hit_2b: '36',
         hit_3b: '2',
         hr: '13',
         tb: '222',
         rbi: '48',
         run: '77',
         so: '102',
         bb: '41',
         ibb: '0',
         hbp: '1',
         sh: '28',
         sf: '2',
         sb: '14',
         cs: '5',
         gdp: '5'
      },
      {
         name: '大山 悠輔（神）',
         picture: open("#{Rails.root}/db/fixtures/1600113_s.jpg"),
         league: 'false',
         game: '143',
         pa: '587',
         ab: '538',
         hit: '139',
         hit_2b: '33',
         hit_3b: '1',
         hr: '14',
         tb: '216',
         rbi: '76',
         run: '52',
         so: '98',
         bb: '39',
         ibb: '3',
         hbp: '5',
         sh: '1',
         sf: '4',
         sb: '3',
         cs: '0',
         gdp: '12'
      },
      {
         name: '京田 陽太 （中）',
         picture: open("#{Rails.root}/db/fixtures/1600107_s.jpg"),
         league: 'false',
         game: '140',
         pa: '574',
         ab: '507',
         hit: '126',
         hit_2b: '14',
         hit_3b: '5',
         hr: '3',
         tb: '159',
         rbi: '40',
         run: '46',
         so: '91',
         bb: '37',
         ibb: '3',
         hbp: '3',
         sh: '24',
         sf: '3',
         sb: '17',
         cs: '7',
         gdp: '10'
      },
      {
         name: 'ロペス（De）',
         picture: open("#{Rails.root}/db/fixtures/1300003_s.jpg"),
         league: 'false',
         game: '142',
         pa: '597',
         ab: '551',
         hit: '133',
         hit_2b: '28',
         hit_3b: '0',
         hr: '31',
         tb: '254',
         rbi: '84',
         run: '69',
         so: '107',
         bb: '39',
         ibb: '6',
         hbp: '4',
         sh: '0',
         sf: '3',
         sb: '0',
         cs: '0',
         gdp: '18'
      },
      {
         name: '大和（De）',
         picture: open("#{Rails.root}/db/fixtures/600003_s.jpg"),
         league: 'false',
         game: '137',
         pa: '490',
         ab: '438',
         hit: '104',
         hit_2b: '17',
         hit_3b: '2',
         hr: '0',
         tb: '125',
         rbi: '37',
         run: '42',
         so: '75',
         bb: '34',
         ibb: '1',
         hbp: '6',
         sh: '10',
         sf: '2',
         sb: '3',
         cs: '1',
         gdp: '7'
      },
      {
         name: '村上 宗隆（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/1700084_s.jpg"),
         league: 'false',
         game: '143',
         pa: '593',
         ab: '511',
         hit: '118',
         hit_2b: '20',
         hit_3b: '0',
         hr: '36',
         tb: '246',
         rbi: '96',
         run: '76',
         so: '184',
         bb: '74',
         ibb: '5',
         hbp: '5',
         sh: '0',
         sf: '3',
         sb: '5',
         cs: '4',
         gdp: '9'
      }
   ]
)
Pitcher.create!(
   [
      {
         name: '大野 雄大（中）',
         picture: open("#{Rails.root}/db/fixtures/1000138_s.jpg"),
         league: 'false',
         win: '9',
         lose: '8',
         game: '25',
         cg: '2',
         sho: '2',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '533',
         tbf: '696',
         hit: '132',
         hr: '18',
         so: '156',
         bb: '43',
         hbp: '2',
         wp: '2',
         bk: '0',
         r: '52',
         er: '51',
         fip: '3.70'
      },
      {
         name: 'ジョンソン（広）',
         picture: open("#{Rails.root}/db/fixtures/1500007_s.jpg"),
         league: 'false',
         win: '11',
         lose: '8',
         game: '27',
         cg: '1',
         sho: '1',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '470',
         tbf: '-',
         hit: '132',
         hr: '12',
         so: '132',
         bb: '58',
         hbp: '4',
         wp: '3',
         bk: '0',
         r: '50',
         er: '45',
         fip: '3.87'
      },
      {
         name: '山口 俊 （巨）',
         picture: open("#{Rails.root}/db/fixtures/600008_s.jpg"),
         league: 'false',
         win: '15',
         lose: '4',
         game: '26',
         cg: '0',
         sho: '0',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '510',
         tbf: '-',
         hit: '137',
         hr: '8',
         so: '188',
         bb: '60',
         hbp: '13',
         wp: '4',
         bk: '0',
         r: '60',
         er: '55',
         fip: '3.08'
      },
      {
         name: '山本 由伸（オ）',
         picture: open("#{Rails.root}/db/fixtures/pitcher_1.jpg"),
         league: 'true',
         win: '8',
         lose: '6',
         game: '20',
         cg: '1',
         sho: '1',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '429',
         tbf: '-',
         hit: '101',
         hr: '8',
         so: '127',
         bb: '36',
         hbp: '3',
         wp: '3',
         bk: '1',
         r: '37',
         er: '31',
         fip: '3.09'
      },
      {
         name: '有原 航平（日）',
         picture:  open("#{Rails.root}/db/fixtures/1400117_s.jpg"),
         league: 'true',
         win: '15',
         lose: '8',
         game: '24',
         cg: '1',
         sho: '1',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '493',
         tbf: '-',
         hit: '111',
         hr: '14',
         so: '161',
         bb: '40',
         hbp: '9',
         wp: '9',
         bk: '0',
         r: '49',
         er: '45',
         fip: '3.36'
      },
      {
         name: '千賀 滉大（ソ）',
         picture: open("#{Rails.root}/db/fixtures/1000174_s.jpg"),
         league: 'true',
         win: '13',
         lose: '8',
         game: '26',
         cg: '2',
         sho: '2',
         qs: '20',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '541',
         tbf: '-',
         hit: '134',
         hr: '19',
         so: '227',
         bb: '75',
         hbp: '8',
         wp: '4',
         bk: '1',
         r: '60',
         er: '56',
         fip: '3.36'
      },
      {
         name: '高橋 礼（ソ）',
         picture: open("#{Rails.root}/db/fixtures/1700130_s.jpg"),
         league: 'true',
         win: '12',
         lose: '6',
         game: '23',
         cg: '0',
         sho: '0',
         qs: '13',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '429',
         tbf: '-',
         hit: '114',
         hr: '10',
         so: '73',
         bb: '49',
         hbp: '11',
         wp: '3',
         bk: '1',
         r: '56',
         er: '53',
         fip: '4.47'
      },
      {
         name: '山岡 泰輔（オ）',
         picture: open("#{Rails.root}/db/fixtures/1600150_s.jpg"),
         league: 'true',
         win: '13',
         lose: '4',
         game: '26',
         cg: '0',
         sho: '0',
         qs: '15',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '510',
         tbf: '-',
         hit: '154',
         hr: '16',
         so: '154',
         bb: '45',
         hbp: '4',
         wp: '2',
         bk: '0',
         r: '77',
         er: '70',
         fip: '3.58'
      },
      {
         name: '美馬 学（楽)',
         picture: open("#{Rails.root}/db/fixtures/1000155_s.jpg"),
         league: 'true',
         win: '8',
         lose: '5',
         game: '25',
         cg: '0',
         sho: '0',
         qs: '13',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '431',
         tbf: '-',
         hit: '146',
         hr: '19',
         so: '112',
         bb: '24',
         hbp: '4',
         wp: '3',
         bk: '0',
         r: '69',
         er: '64',
         fip: '4.07'
      },
      {
         name: '今永 昇太（De）',
         picture: open("#{Rails.root}/db/fixtures/1500061_s.jpg"),
         league: 'false',
         win: '13',
         lose: '7',
         game: '25',
         cg: '3',
         sho: '3',
         qs: '17',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '510',
         tbf: '-',
         hit: '128',
         hr: '18',
         so: '186',
         bb: '56',
         hbp: '4',
         wp: '2',
         bk: '0',
         r: '59',
         er: '55',
         fip: '3.52'
      },
      {
         name: '西 勇輝（神）',
         picture: open("#{Rails.root}/db/fixtures/900062_s.jpg"),
         league: 'false',
         win: '10',
         lose: '8',
         game: '26',
         cg: '1',
         sho: '1',
         qs: '19',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '517',
         tbf: '-',
         hit: '159',
         hr: '12',
         so: '112',
         bb: '36',
         hbp: '9',
         wp: '2',
         bk: '0',
         r: '60',
         er: '56',
         fip: '3.77'
      },
      {
         name: '大瀬良 大地（広）',
         picture: open("#{Rails.root}/db/fixtures/1300057_s.jpg"),
         league: 'false',
         win: '11',
         lose: '9',
         game: '26',
         cg: '6',
         sho: '2',
         qs: '16',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '520',
         tbf: '-',
         hit: '176',
         hr: '22',
         so: '136',
         bb: '35',
         hbp: '4',
         wp: '4',
         bk: '0',
         r: '72',
         er: '68',
         fip: '4.13'
      },
      {
         name: '柳 裕也（中）',
         picture: open("#{Rails.root}/db/fixtures/1600106_s.jpg"),
         league: 'false',
         win: '11',
         lose: '7',
         game: '26',
         cg: '1',
         sho: '0',
         qs: '18',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '512',
         tbf: '-',
         hit: '165',
         hr: '21',
         so: '146',
         bb: '38',
         hbp: '3',
         wp: '3',
         bk: '0',
         r: '69',
         er: '67',
         fip: '3.99'
      },
      {
         name: '小川 泰弘（ヤ）',
         picture: open("#{Rails.root}/db/fixtures/1200076_s.jpg"),
         league: 'false',
         win: '5',
         lose: '12',
         game: '26',
         cg: '2',
         sho: '1',
         qs: '13',
         hld: '0',
         hp: '0',
         sv: '0',
         o: '479',
         tbf: '-',
         hit: '173',
         hr: '26',
         so: '132',
         bb: '36',
         hbp: '2',
         wp: '1',
         bk: '0',
         r: '91',
         er: '81',
         fip: '4.59'
      }
   ]
)